// Attaches profile-independent LegFare facts to each transit leg of an
// already-built RouteResult[], using the GTFS index generated by
// scripts/generate-fare-index.ts. Runs server-side only (see
// src/lib/plan-query.ts's buildRoutes) — the index is ~700KB and has no
// reason to reach the client, since re-pricing for a different rider profile
// needs no refetch (see src/lib/fares/price.ts).
//
// Deliberately keyed off RouteLeg.routeGtfsId, which PLAN_QUERY already
// requests (`route { gtfsId shortName }`) for an unrelated reason (matching
// traffic estimates — see its own comment in types.ts). No GraphQL query
// change was needed for fares as a result.
import { RouteResult } from '../types'
import gtfsIndex from './gtfs-index.json'

interface GtfsIndex {
  authorities: string[]
  routeAuthority: Record<string, number>
  routeAgency: Record<string, string>
  agencyFareUrl: Record<string, string>
}

const index = gtfsIndex as GtfsIndex

export function attachLegFares(routes: RouteResult[]): void {
  for (const route of routes) {
    for (const leg of route.legs) {
      if (leg.mode === 'walk' || !leg.routeGtfsId) continue

      const authorityIdx = index.routeAuthority[leg.routeGtfsId]
      if (authorityIdx === undefined) continue

      const agencyId = index.routeAgency[leg.routeGtfsId]
      const fareUrl = agencyId ? index.agencyFareUrl[agencyId] : undefined

      leg.fare = { authority: index.authorities[authorityIdx], fareUrl }
    }
  }
}
