// Hand-maintained Estonian fare table, keyed by the exact `competent_authority`
// string from routes.txt (see src/lib/fares/gtfs-index.json, generated by
// scripts/generate-fare-index.ts). This file is the one place a maintainer
// changes a number when an operator raises its fares — every row carries the
// page it was checked against and the date it was last verified, because
// Estonian transit fares change several times a year and a stale number here
// is a wrong price shown with full confidence.
//
// An authority with no row here is deliberately unpriced: src/lib/fares/price.ts
// reports `evidence: 'unknown'` rather than defaulting to free or to some other
// authority's price. Only add a row once you have an actual source for it —
// never estimate by analogy to a neighbouring county or city.

export type RiderCategory = 'child' | 'youth' | 'adult' | 'senior'

export interface RiderProfile {
  ageBand: RiderCategory
  // A CITIES id (src/lib/constants.ts) — set when the rider is a *registered*
  // resident of that city, which is what Tallinn's free-transit scheme and
  // Tartu's resident discount actually key off, not merely "traveling in
  // Tallinn today".
  residentOf?: string
}

export type TariffKind = 'flat' | 'demand' | 'commercial'

export interface Tariff {
  authority: string
  kind: TariffKind
  // When this row was last checked against `source` — shown to the rider as
  // "prices as of {date}" so an out-of-date number reads as a caveat, not a
  // fact. Not necessarily the fare's own effective date, which secondary
  // sources often disagree on.
  updatedOn: string
  source: string
  // Fallback link when the specific leg's own operator has no agency_fare_url
  // in the feed (see LegFare.fareUrl, which wins when present).
  fareUrl: string
  // A rider boarding a second leg under this same authority within this many
  // seconds of the first boarding rides on one ticket, not two — matches each
  // operator's own published transfer validity, not a single global constant.
  transferWindowSeconds: number
  // kind: 'flat' — what every rider profile pays, in cents.
  priceCents?: Record<RiderCategory, number>
  // kind: 'flat' only, and only when this authority discounts registered
  // residents of one specific city (a CITIES id) below `priceCents` — Tallinn
  // (free) and Tartu (reduced) both use this, just with different numbers.
  residentOf?: string
  residentPriceCents?: Record<RiderCategory, number>
  // kind: 'demand' — Elron moved to demand-based pricing, so this table can
  // only ever be a floor. Rendered as "from €X", never as an exact total.
  floorPriceCents?: Record<RiderCategory, number>
}

const FREE: Record<RiderCategory, number> = { child: 0, youth: 0, adult: 0, senior: 0 }

// County bus networks (maakonnaliinid) — a single national e-ticket scheme
// replaced the old per-county tariffs. Note: the national GTFS feed still
// ships a zoned fare_attributes.txt for Harju/Rapla (e.g. "Harju 2 tsooni"
// 2.00 EUR) left over from before that reform, and three of its own rows
// mislabel the currency as USD — both signs it's stale, so it's deliberately
// not used here in favour of the current flat scheme confirmed live below.
// Source: https://maakonnad.pilet.ee/et/purchase/ticket ,
// https://www.err.ee/1609363580/maakonnaliinide-piletihindade-piirmaarad-kerkivad-huppeliselt
// — single 1.5h e-ticket €1.50 (20-62), free under 20 and from 63.
const COUNTY_AUTHORITIES = [
  'Harjumaa',
  'Tartumaa',
  'Ida-Virumaa',
  'Pärnumaa',
  'Viljandimaa',
  'Lääne-Virumaa',
  'Saaremaa',
  'Läänemaa',
  'Raplamaa',
  'Järvamaa',
  'Jõgevamaa',
  'Põlvamaa',
  'Valgamaa',
  'Võrumaa',
  'Hiiumaa',
] as const

function countyTariff(authority: string): Tariff {
  return {
    authority,
    kind: 'flat',
    updatedOn: '2026-08-27',
    source: 'https://maakonnad.pilet.ee/et/purchase/ticket',
    fareUrl: 'https://maakonnad.pilet.ee/',
    transferWindowSeconds: 90 * 60,
    priceCents: { child: 0, youth: 0, adult: 150, senior: 0 },
  }
}

export const TARIFFS: Record<string, Tariff> = {
  ...Object.fromEntries(COUNTY_AUTHORITIES.map((a) => [a, countyTariff(a)])),

  // Tallinn city transport is free for registered Tallinn residents — the
  // headline feature of its whole fare model. Non-residents pay a standard
  // and a discount rate; the single published "soodushind" is used for
  // child/youth/senior alike since Tallinn's own price list gives one
  // discount figure rather than three.
  // Source: https://tallinntram.com/piletid-ja-hinnad/
  'Tallinna linn': {
    authority: 'Tallinna linn',
    kind: 'flat',
    updatedOn: '2026-08-27',
    source: 'https://tallinntram.com/piletid-ja-hinnad/',
    fareUrl: 'https://tallinn.pilet.ee/',
    transferWindowSeconds: 60 * 60,
    priceCents: { child: 100, youth: 100, adult: 200, senior: 100 },
    residentOf: 'tallinn',
    residentPriceCents: FREE,
  },

  // Tartu discounts registered Tartu residents rather than making transit
  // free outright. No separate child/youth/senior fare was found in the
  // source, so the same two numbers apply to every rider category.
  // Source: https://tartu.ee/et/uudised/1-juulist-tousevad-tartus-uhistranspordi-ja-rattaringluse-piletihinnad
  'Tartu linn': {
    authority: 'Tartu linn',
    kind: 'flat',
    updatedOn: '2026-08-27',
    source: 'https://tartu.ee/et/uudised/1-juulist-tousevad-tartus-uhistranspordi-ja-rattaringluse-piletihinnad',
    fareUrl: 'https://tartu.pilet.ee/et/home',
    transferWindowSeconds: 60 * 60,
    priceCents: { child: 180, youth: 180, adult: 180, senior: 180 },
    residentOf: 'tartu',
    residentPriceCents: { child: 120, youth: 120, adult: 120, senior: 120 },
  },

  // Pärnu's own discount structure (age/resident) wasn't found in the source
  // beyond the single card-payment price, so that one number is used for
  // every rider category — never invented, but also not assumed free.
  // Source: https://pytk.ee/piletihinnad-ja-soodustused.html
  'Pärnu linn': {
    authority: 'Pärnu linn',
    kind: 'flat',
    updatedOn: '2026-08-27',
    source: 'https://pytk.ee/piletihinnad-ja-soodustused.html',
    fareUrl: 'https://parnu.pilet.ee/buy',
    transferWindowSeconds: 60 * 60,
    priceCents: { child: 150, youth: 150, adult: 150, senior: 150 },
  },

  // Elron moved to demand-based pricing — this can only ever be a floor
  // (the lowest published e-channel zone-1 fare), never an exact quote.
  // Rendered as "from €X" with evidence 'floor'. Family/child concessions
  // likely exist but weren't confirmed, so the same floor is used for every
  // category rather than guessing a discount.
  // Source: https://www.err.ee/1610100334/elroni-piletihinnad-tousid-1-augustist-tallinnas-sees-ja-lahiumbroses
  Elron: {
    authority: 'Elron',
    kind: 'demand',
    updatedOn: '2026-08-27',
    source: 'https://www.err.ee/1610100334/elroni-piletihinnad-tousid-1-augustist-tallinnas-sees-ja-lahiumbroses',
    fareUrl: 'https://elron.ee/piletiinfo/piletid',
    transferWindowSeconds: 0,
    floorPriceCents: { child: 200, youth: 200, adult: 200, senior: 200 },
  },

  // Commercial long-distance coach lines (Lux Express, GoBus intercity,
  // various small operators) — each sets and changes its own dynamic prices,
  // with no shared tariff to table. Never quote a number; link out instead.
  // The per-leg agency_fare_url (see LegFare.fareUrl) almost always overrides
  // this generic fallback since REM spans a dozen unrelated operators.
  REM: {
    authority: 'REM',
    kind: 'commercial',
    updatedOn: '2026-08-27',
    source: 'n/a — dynamically priced by each operator',
    fareUrl: 'https://www.tpilet.ee/',
    transferWindowSeconds: 0,
  },

  // TS Laevad — flat pedestrian fare on both island ferry lines regardless
  // of distance. Under-7s free; the 7-14 half-price rate is used as the
  // 'youth' figure though it may not extend to 15-19 (unverified); senior
  // is the published ~50% concession rounded to the nearest cent.
  // Source: https://www.praamid.ee/hinnad-ja-soodustused/
  'TS Laevad': {
    authority: 'TS Laevad',
    kind: 'flat',
    updatedOn: '2026-08-27',
    source: 'https://www.praamid.ee/hinnad-ja-soodustused/',
    fareUrl: 'https://www.praamid.ee/hinnad-ja-soodustused/',
    transferWindowSeconds: 0,
    priceCents: { child: 0, youth: 220, adult: 430, senior: 220 },
  },

  // No published, verifiable tariff found for these city networks within
  // this pass — deliberately left unmapped rather than guessed. A leg on
  // 'Narva linn' / 'Kohtla-Järve linn' / 'Rakvere linn' / 'Sillamäe linn' /
  // 'Jõhvi linn' resolves to evidence: 'unknown' until a maintainer adds a
  // sourced row here.
}
